services:
  yhoro-website:
    image: ghcr.io/youssef-horo/website:${IMAGE_TAG:-1.5.0}
    container_name: yhoro-website
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true

