services:
  cv-template:
    image: nextjs-cv-template:${IMAGE_TAG:-latest}
    container_name: cv-template
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "8080:8080"

